version: '3.8'

services:
  return-percentage:
    container_name: return-percentage-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge